# Generated by Django 3.1.6 on 2021-02-24 07:44

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210224_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください', verbose_name='本文'),
        ),
    ]
